// SPDX-License-Identifier: GPL-2.0-or-later
// ─────────────────────────────────────────────────────────────────
// keymap.c — Vial default keymap
// Generated by QMK/Vial Wizard v5.6 on 2026-04-17
// ─────────────────────────────────────────────────────────────────
// MATRIX DIMENSIONS: 5 rows × 14 cols
// (Single board: 5 rows)
//

#include QMK_KEYBOARD_H

// Dummy arrays for QMK introspection
#if defined(COMBO_ENABLE)
combo_t key_combos[] = {};
#endif

#if defined(TAP_DANCE_ENABLE)
tap_dance_action_t tap_dance_actions[] = {};
#endif

#if defined(KEY_OVERRIDE_ENABLE)
const key_override_t *key_overrides[] = {};
#endif

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [0] = LAYOUT(

        QK_GESC,  KC_1,     KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,     KC_0,     KC_MINS,    KC_EQL,    KC_BSPC,    KC_BSLS,
        KC_TAB,   KC_Q,     KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,     KC_P,     KC_LBRC,    KC_RBRC,   KC_BSLS,
        KC_LCTL,  KC_A,     KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,     KC_SCLN,  KC_QUOT,    KC_ENT,
        KC_LSFT,            KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM,  KC_DOT,   KC_SLSH,    MT(MOD_RSFT, KC_UP), MO(1),
        KC_LCTL,  KC_LGUI,  KC_LALT,                            KC_SPC,                                        MT(MOD_RALT, KC_LEFT),    MT(MOD_RGUI, KC_DOWN),  MT(MOD_RCTL, KC_RGHT)

    )

};

