// SPDX-License-Identifier: GPL-2.0-or-later
// ─────────────────────────────────────────────────────────────────
// keymap.c — Vial default keymap
// Generated by QMK/Vial Wizard v5.6 on 2026-04-17
// ─────────────────────────────────────────────────────────────────
// MATRIX DIMENSIONS: 5 rows × 14 cols
// (Single board: 5 rows)
//

#include QMK_KEYBOARD_H

// Dummy arrays for QMK introspection
#if defined(COMBO_ENABLE)
combo_t key_combos[] = {};
#endif

#if defined(TAP_DANCE_ENABLE)
tap_dance_action_t tap_dance_actions[] = {};
#endif

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [0] = LAYOUT(

        QK_GESC,  KC_1,     KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,     KC_0,     KC_MINS,    KC_EQL,    KC_BSPC,    KC_BSLS,
        KC_TAB,   KC_Q,     KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,     KC_P,     KC_LBRC,    KC_RBRC,   KC_BSLS,
        KC_CAPS,  KC_A,     KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,     KC_SCLN,  KC_QUOT,    KC_ENT,
        KC_LSFT,            KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM,  KC_DOT,   KC_SLSH,    MT(MOD_RSFT, KC_UP), MO(1),
        KC_LCTL,  KC_LGUI,  KC_LALT,                            KC_SPC,                                        MT(MOD_RALT, KC_LEFT),    MT(MOD_RGUI, KC_DOWN),  MT(MOD_RCTL, KC_RGHT)

    ),
    [1] = LAYOUT(

        KC_GRV,   KC_F1,    KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,    KC_F10,   KC_F11,     KC_F12,    KC_DEL,    KC_BSLS,
        KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS,  KC_TRNS,    KC_TRNS,   KC_TRNS,
        KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS,  KC_TRNS,    KC_TRNS,
        KC_TRNS,            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS,  KC_TRNS,    KC_VOLU,   KC_TRNS,
        KC_TRNS,  KC_TRNS,  KC_TRNS,                            KC_TRNS,                                       KC_HOME,    KC_VOLD,   KC_END

    ),
    [1] = LAYOUT(

        KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS,  KC_TRNS,    KC_TRNS,   KC_TRNS,    KC_TRNS,
        KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS,  KC_TRNS,    KC_TRNS,   KC_TRNS,
        KC_TRNS,  KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS,  KC_TRNS,    KC_TRNS,
        KC_TRNS,            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS,  KC_TRNS,    KC_TRNS,   KC_TRNS,
        KC_TRNS,  KC_TRNS,  KC_TRNS,                            KC_TRNS,                                       KC_TRNS,    KC_TRNS,   KC_TRNS

    )

};


const key_override_t ctrl_1_override = ko_make_basic(MOD_MASK_CS, KC_1, KC_F1);
const key_override_t ctrl_2_override = ko_make_basic(MOD_MASK_CS, KC_2, KC_F2);
const key_override_t ctrl_3_override = ko_make_basic(MOD_MASK_CS, KC_3, KC_F3);
const key_override_t ctrl_4_override = ko_make_basic(MOD_MASK_CS, KC_4, KC_F4);
const key_override_t ctrl_5_override = ko_make_basic(MOD_MASK_CS, KC_5, KC_F5);
const key_override_t ctrl_6_override = ko_make_basic(MOD_MASK_CS, KC_6, KC_F6);
const key_override_t ctrl_7_override = ko_make_basic(MOD_MASK_CS, KC_7, KC_F7);
const key_override_t ctrl_8_override = ko_make_basic(MOD_MASK_CS, KC_8, KC_F8);
const key_override_t ctrl_9_override = ko_make_basic(MOD_MASK_CS, KC_9, KC_F9);
const key_override_t ctrl_0_override = ko_make_basic(MOD_MASK_CS, KC_0, KC_F10);
const key_override_t ctrl_min_override = ko_make_basic(MOD_MASK_CS, KC_MINS, KC_F11);
const key_override_t ctrl_eql_override = ko_make_basic(MOD_MASK_CS, KC_EQL, KC_F12);

const key_override_t alt_bspc_override = ko_make_basic(MOD_MASK_ALT, KC_BSPC, KC_DEL);

const key_override_t *key_overrides[] = {
    &ctrl_1_override,
    &ctrl_2_override,
    &ctrl_3_override,
    &ctrl_4_override,
    &ctrl_5_override,
    &ctrl_6_override,
    &ctrl_7_override,
    &ctrl_8_override,
    &ctrl_9_override,
    &ctrl_0_override,
    &ctrl_min_override,
    &ctrl_eql_override,
    &alt_bspc_override,
    NULL // Terminate the array (Required)
};
